package com.dczajkowski.bookmanager;

public enum Genre {
    ACTION,
    ALTERNATE_HISTORY,
    AUTOBIOGRAPHY,
    BIOGRAPHY,
    CHILDRENS_LITERATURE,
    COOKBOOK,
    COMIC_BOOK,
    DICTIONARY,
    CRIME,
    ENCYCLOPEDIA,
    DRAMA,
    GUIDE,
    FAIRYTALE,
    FANTASY,
    HISTORY,
    MATH,
    HORROR,
    MYSTERY,
    POETRY,
    REVIEW,
    SCIENCE,
    ROMANCE,
    SATIRE,
    TRAVEL,
    SCIENCE_FICTION,
    THRILLER,
}
